[package]
name = "network_scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smoltcp = "0.9.1"
tuntap = "0.2.0"
tokio = { version = "1.14.0", features = ["full"] }
libpcap = "0.1"